# Generated by Django 2.0.4 on 2018-04-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
