# Generated by Django 2.0.4 on 2018-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0002_news_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date_created',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
