# Generated by Django 2.0.4 on 2018-04-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='news_api.News'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
