# Generated by Django 2.0.4 on 2018-04-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0007_auto_20180425_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='votes_dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='news',
            name='votes_likes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
