# Generated by Django 2.0.4 on 2018-04-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0008_auto_20180425_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='votes_dislikes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='votes_likes',
        ),
    ]
